import = [
  "~/.config/alacritty/themes/themes/zenburn.toml"
]

#background_opacity = 1.0
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0


[scrolling]
history = 5000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = true
startup_mode = "Windowed"

[window.padding]
x = 2
y = 2
