add_newline = false

format = '''
$time $directory $golang $git_branch $git_status $character
'''

[directory]
style = 'white'
truncate_to_repo = false
truncation_length = 0
format = "[$path]($style)[$read_only]($read_only_style)"

[azure]
disabled = true
[aws]
disabled = true

[git_branch]
style = "green"
format = "[$symbol$branch(:$remote_branch)]($style)"

[time]
disabled = false
time_format = '%T'
utc_time_offset = 'local'

[golang]
format = ' [$symbol($version )($mod_version )]($style)'
